server:
  port: 9000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: auction
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    jdbc:
      audit: off
      resultset: off
      connection: off
      sqlonly: off