server:
  port: 9000

spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mariadb://localhost:3306/orderservice
    url: jdbc:log4jdbc:mariadb://localhost:3306/auction
    username: root
    password: root

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml